Algoritmo "Media ulbra"
Var
Ap1, Ap2, AS, MD: real
Inicio
      escreval ("Digite a primeira nota")
      leia (Ap1)
      escreval ("Digite a segunda nota")
      leia (Ap2)
      escreval ("Digite a terceira nota")
      leia (AS)
      MD <- Ap1 + Ap2 + AS
      escreval ("Sua média é:" ,MD)
      se MD>=7 entao
      escreval ("Aprovado")
      senao
      escreval ("Precisa fazer AF")

FIMSE
Fimalgoritmo